### ISSUE TITLE
com.red5pro.subscribe loop (50): exc_bad_access (code=1, address=0xd69a3bec8)

### ISSUE THREAD

**Issue by RamNalluri** [red5pro/streaming-ios#139]
Got crash while subscribe multiple audio streams...

**Comment by aly-irshad** [comment]
Hello
Any update for this. I am getting the same error

**Comment by HoldenMills** [comment]
Hello. Thanks for reaching out to us. Please provide our support team with more information by submitting a ticket using this link: https://red5pro.zendesk.com/hc/en-us/requests/new.

Please make sure to provide additional details such as reproduction steps to speed up the process.

Thanks!
