### ISSUE TITLE
If a R5Stream hasn't been started, call stop will crash the app

### ISSUE THREAD

**Issue by caoer** [red5pro/streaming-ios#140]
During our testing of the production app. If an R5Stream hasn't been started, call stop will crash the app. We have added necessary steps to prevent it from happening. 

The crash lines at: 

```
global.c - Line 81
r5_cancel_license_validation
```

It should be the SDK's responsibility to keep it as stable as possible. please add the necessary check and avoid crashing. If the R5Stream is in 'action', like publishing and subscribing, or trying to `publishing and subscribing`, calling stop should stop the action. if the R5Stream is not in an actionable state, calling stop should do nothing.

**Comment by beetlejesss** [comment]
Thank you @caoer for bringing this to our attention! The fix will be included in our next SDK release.
