### ISSUE TITLE
R5ProObjectiveCExamples build error

### ISSUE THREAD

**Issue by cosminstirbu** [red5pro/streaming-ios#157]
Hello,

I'm trying to run R5ProObjectiveCExamples and I receive the following error:

`/Users/cosminstirbu/Downloads/streaming-ios-master/R5ProObjectiveCExamples/R5ProObjectiveCExamples/Tests/BaseTest.h:10:9: 'R5Streaming/R5Streaming.h' file not found`

I receive this error on both real device (iPhone XS) and simulator.

All I've done was to download the repo as a .zip, open R5ProObjectiveCExamples.xcodeproj and hit Run.

Any help with this would be appreciated,
Cosmin

**Comment by HoldenMills** [comment]
Hello. Thank you for taking a look at Red5 Pro!
Please submit a support ticket by following this link: https://red5pro.zendesk.com/hc/en-us/requests/new 
The Support Desk will be able to address your issue.

Thanks,
Holden
