### ISSUE TITLE
R5VideoController memory leaks

### ISSUE THREAD

**Issue by cosminstirbu** [red5pro/streaming-ios#162]
Hello,

In the attached sample, if I profile the application (using Allocations) and navigate to the subscribing screen forward and backwards several times, you'll see that the memory keeps increasing, and if you search for R5 related instances, one that leaks is R5VideoController.

Please prioritize this as if you'll do the profiling your own, you'll see that the SDK leaked around 20 mb for each forward and backwards navigation.

[Red5Test.zip](https://github.com/red5pro/streaming-ios/files/3201537/Red5Test.zip)

![Screenshot 2019-05-21 at 11 19 59](https://user-images.githubusercontent.com/7135690/58081093-17369800-7bbd-11e9-9d4e-55e7887a6bae.png)

Thank you,
Cosmin

**Comment by beetlejesss** [comment]
Hi @cosminstirbu could you please try this with the latest SDK (5.6.0) which was released earlier this week. If you are still seeing the problem, then please submit at ticket via the Red5 Pro help desk so it can be tracked - https://red5pro.zendesk.com/hc/en-us/requests/new
thank you.

**Comment by cosminstirbu** [comment]
The issue reproduces with 5.6.0 version as well.

**Comment by HoldenMills** [comment]
Sorry to hear that this is still an issue. Please submit a ticket via the Red5 Pro help desk so it can be tracked - https://red5pro.zendesk.com/hc/en-us/requests/new
thank you.
