### ISSUE TITLE
Live Video Streaming in IOS

### ISSUE THREAD

**Issue by nirav700** [red5pro/streaming-ios#23]
Hello Team,

```
     I have mobile application where we have module like Live Video Streaming , So my question is that is Red5Pro provide IOS SDK where user can see live video streaming through mobile application.

   Let me give you my requirements , suppose one user going to record live video and that video will be seen by his/her friends instantly so is it possible through from Red5Pro IOS SDK ? what i should need for  implement that module ? where is it stored all live video ?

 can you please guide me on to this. 
```

**Comment by HoldenMills** [comment]
Hello! 

Thank you for your question.  Yes, this is certainly something you can do with Red5Pro.  

Please take a look at the following documentation for more information:

[https://blog.red5pro.com/how-to-converting-recorded-files-to-mp4-for-seamless-playback-via-red5-pro](https://blog.red5pro.com/how-to-converting-recorded-files-to-mp4-for-seamless-playback-via-red5-pro/)

[https://red5pro.zendesk.com/hc/en-us/articles/216704167-Stream-Recording](https://red5pro.zendesk.com/hc/en-us/articles/216704167-Stream-Recording)

[https://red5pro.zendesk.com/hc/en-us/articles/216136728-Android-Stream-Recording](https://red5pro.zendesk.com/hc/en-us/articles/216136728-Android-Stream-Recording)

If there is anything else we can help you with please let us know using [this link](https://red5pro.zendesk.com/hc/en-us/requests/new
).  We are always happy to help!

Cheers,
Holden
