### ISSUE TITLE
[R5 ERROR] on_connect error: connection refused

### ISSUE THREAD

**Issue by bintu1234** [red5pro/streaming-ios#28]
Hi when i start publish then it is showing "connection refused" error. and I am using Red5 server when i give my servername likertmp://server.tv/server/stream. But I don't know where i am missing can you please Guide me 
Thankyou

**Comment by HoldenMills** [comment]
Hello,

If you are testing locally, please make sure that your testing device is using the same network as the system that is running the server.  Please make sure the following ports are open on your system 
5080 : default web access of Red5
1935 : default Red5 RTMP port
8554 : default RTSP port

If you have any questions, please do not hesitate to ask us on our website.
[](https://red5pro.zendesk.com/hc/en-us/requests/new)

Hope that helps!

Thanks,
Holden

**Comment by beetlejesss** [comment]
Other possibilities:  try publishing to the server IP address, not the domain name. Also - the SDKs only work with Red5 Pro (www.red5pro.com), not Red5 open source server.
