### ISSUE TITLE
License

### ISSUE THREAD

**Issue by bintu1234** [red5pro/streaming-ios#29]
Hi i am  working on Broadcast  so i just tried with this Library founded in Github. But is it open Source or paid Library 
Thanks

**Comment by mrchrisallen** [comment]
Red5 Pro is a paid licensed product, but we designed the SDK and server to be extremely flexible and extensible. You can embed the SDK in any app you choose to create a live streaming experience, and it's a pretty simple to use. If it doesn't do what you need, I would love to hear what that is so we can help make our SDK even better. You will need the Red5 Pro server which you can download from our website: http://red5pro.com in order for the iOS SDK to work. 

Let me know if you have other questions and good luck with your app.

**Comment by scaudle** [comment]
Hi 
Just download both Pro server and installed and the ios build. I am running on xcode 8 and device is ios 10 dev last build. App crashes after you enter publish. Will this be updated soon? Ios 10 releases in 7 days

**Comment by beetlejesss** [comment]
When iOS 10 is officially released, we will update our apps accordingly.
