### ISSUE TITLE
More then one subscribe stream

### ISSUE THREAD

**Issue by abakhtin** [red5pro/streaming-ios#30]
Hi guys,
Can you help me with my issue?
I have a requirement to subscribe several streams at once. I tried to present two R5VideoViewController but only the first one is showing data. The second one is black.
Do you have/test a such functionality? Do I miss something?

Edit:
Actually I can not find any info about it in the reference or google else.

**Comment by HoldenMills** [comment]
Hello,

Here is an example app that will help you do that:
[https://github.com/red5pro/ios-streaming-testbed/tree/master/R5ProTestbed/Tests/DoubleSubscriber](https://github.com/red5pro/ios-streaming-testbed/tree/master/R5ProTestbed/Tests/DoubleSubscriber)

Please [let us know](https://red5pro.zendesk.com/hc/en-us/requests/new) if you have any other questions.  We are always happy to help!

Cheers,
Holden

**Comment by abakhtin** [comment]
Thank you for reply,
I have added issue on you help desk,
Please, let me know when issue will be fixed.

Thanks a lot for information.

**Comment by vishalchauhan** [comment]
Is this issue resolved as I am facing the same issue

**Comment by vishalchauhan** [comment]
@abakhtin I am using the sample provides at GitHub along with SDK 1.2 but I am able to see only the first stream the second one goes black. Could you please point me to the latest samples?

**Comment by beetlejesss** [comment]
Are you looking at this example?  https://github.com/red5pro/ios-streaming-testbed/tree/master/R5ProTestbed/Tests/SubscribeTwoStreams

**Comment by vishalchauhan** [comment]
@beetlejesss  
Thanks for the Sample link. I was creating my own sample using two way chat, will check with this example.

**Comment by vishalchauhan** [comment]
Thanks @beetlejesss it works.
