### ISSUE TITLE
Red 5 pro camera stopped background music.

### ISSUE THREAD

**Issue by TwinkleMali** [red5pro/streaming-ios#46]
I have integrated red 5 pro in my application.
i wish to continue playing background music while live streaming is running.
but as i started live streaming, the background music stop playing. and after live streaming is done, i am trying to record video but only video is recorded but not audio. so while composing this  two thing i m not getting audio track , so my application is keep crashing for this case.

Please suggest any solution.

**Comment by HoldenMills** [comment]
Hello.  Is the video recording any audio at all?  Is your application crashing or just not working as you would like it to?

**Comment by TwinkleMali** [comment]
hi @HoldenMills ,
      Before i will start live streaming, if i do video recording than audio sound is recorded fine while video recording, 
but once after live streaming is done , and i try to do video recording at that time i am not getting audio track while composition. so my app is crashing .

> My app is crashing on this line.
` AVAssetTrack *clipAudioTrack = [[videoAsset tracksWithMediaType:AVMediaTypeAudio] objectAtIndex:0];`

And i am managing audio session manually, for continue playing background music when camera is open.

Please suggest any solution.

Thanks,
Twinkle

**Comment by HoldenMills** [comment]
@TwinkleMali It sounds like you are looking for a custom audio source, which is a feature we do not support at this time.  If this is something you are interested in, we could look into setting up a custom work contract with you.  Please let me know if you would like more info on that.
