### ISSUE TITLE
R5Configuration Questions

### ISSUE THREAD

**Issue by ropc** [red5pro/streaming-ios#52]
What are valid R5Configuration.protocol values? And what is the difference between R5Configuration.buffer_time and R5Configuration.stream_buffer_time?

**Comment by HoldenMills** [comment]
Please see our API iOS documentation of the R5Configuration class: https://www.red5pro.com/docs/static/ios-streaming/interface_r5_configuration.html#adc2f85d5cd9a9bf0d249c2c7aee5bc03

**Comment by ropc** [comment]
Hello, that link does not describe any possible values for R5Configuration.protocol. From what I've seen in the project is that this just gets set to 1, I was wondering why.

**Comment by HoldenMills** [comment]
The reason we set the buffer_time to 1 is to ensure that the application runs smoothly.  If you are looking for lower latency we recommend something like 0.1 or 0.2 to ensure a better quality stream.  You can certainly experiment to see what works best with you network setup.
