### ISSUE TITLE
[R5 ERROR] Error closing main loop: resource busy or locked

### ISSUE THREAD

**Issue by danlniel** [red5pro/streaming-ios#86]
Hello,
When i try to subscribe or publish i always got this error,
even though the response 200 Ok and connected,
Thank you.

**Comment by HoldenMills** [comment]
Hello.  My apologies for the delay in getting back to you.  Could you please fill out a [support ticket ](https://red5pro.zendesk.com/hc/en-us/requests/new) so we can track your issue.  Thank you.
