### ISSUE TITLE
Suggest us which language is mostly preferable

### ISSUE THREAD

**Issue by shankar667** [red5pro/streaming-ios#93]
Hi Support,

Please suggest us to choose the most prefered  iOS language (Objective-C/Swift) consideing memory utilization and performance for large project with Red5Pro live stream (Publishing).

**Comment by HoldenMills** [comment]
Hello Shankar.  Swift is the more modern language so that would probably be the better choice for you.  Also, our [iOS example](https://github.com/red5pro/streaming-ios) is written in Swift.

**Comment by shankar667** [comment]
Many thanks!
