### ISSUE TITLE
app crach Assertion failed: ((stream->type == UV_TCP || stream->type == UV_NAMED_PIPE)

### ISSUE THREAD

**Issue by mohammadshalhoob** [red5pro/streaming-ios#99]
app crach randomly and i get this message .
Assertion failed: ((stream->type == UV_TCP || stream->type == UV_NAMED_PIPE) && "uv_shutdown (unix) only supports uv_handle_t right now"), function uv_shutdown, file /Users/azupko/Downloads/libuv1/src/unix/stream.c, line 1161.

test on ipad pro , iphone 4s , swift example .

thanks

**Comment by beetlejesss** [comment]
@mohammadshalhoob Are you seeing this crash with this project, or with your own customized code?
We have recently released updated iOS SDK 4.0.0. Please update your project with this SDK and see if that resolves your issue. If it does not, then please submit a ticket to the help desk (https://red5pro.zendesk.com/hc/en-us/requests/new) with the full details of what is happening when you get this crash. If you don't want to share your project with us, then please include an xocde sample project that reproduces the issue.

**Comment by mohammadshalhoob** [comment]
@beetlejesss with this project , i will update sdk to 4.0.0 and see .

thanks

**Comment by mohammadshalhoob** [comment]
yes sdk 4.0.0 fix it .

thank you .
